spring:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      settings:
        web-allow-others: true

server:
  port: 8003

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

  metrics:
    tags:
      application: ${spring.application.name}
      environment: prod

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8002/eureka}
