server:
  port: 8002

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

  metrics:
    tags:
      application: ${spring.application.name}
      environment: prod

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      default-zone: ${EUREKA_URI:http://discUser:discPassword@localhost:8002/eureka}

spring:
  redis:
    host: localhost
    port: 6379
