spring:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      settings:
        web-allow-others: true
  redis:
    host: localhost
    port: 6379

server:
  port: 8004

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

  metrics:
    tags:
      application: ${spring.application.name}
      environment: prod

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8002/eureka}
